### ISSUE TITLE
Error on client start

### ISSUE THREAD

**Issue by MBoberski** [design1online/WTF-Adventure#21]
Hello when I try do lunch: npm start I get:

```
ERROR in ./css/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./css/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir '/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./css/main.scss 2:14-119
 @ multi ./css/main.scss ./src/client/config.json ./assets/data/sprites.json ./assets/data/maps/world_client.json
```

Any idea how to fix that?
TIA

**Comment by MBoberski** [comment]
Also when Starting server I get:

```
Successfully established connection to the MySQL database!
setting timeout, initializing worlds
[nodemon] Internal watch failed: watch /var/www/sites/*.expij.online/html/mmo.expij.online/html/assets/img/common/star.png ENOSPC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WTF-Adventure@1.0.6 wtfserver: `nodemon --exec babel-node src/server/js/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WTF-Adventure@1.0.6 wtfserver script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-12T01_40_54_431Z-debug.log
```

**Comment by MBoberski** [comment]
But it seems to be running... server I mean

**Comment by MBoberski** [comment]
Ok I fixed client error, but still server lunch witch error above. Albo when I log in I cannot move my havvacter at all, sometimes also there is no mag gfx etc.

**Comment by MBoberski** [comment]
I get a lot of:

```
13 verbose stack Error: WTF-Adventure@1.0.6 start: `webpack --mode=development`
13 verbose stack Exit status 143
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
4 verbose pkgid WTF-Adventure@1.0.6

```

**Comment by MBoberski** [comment]
One more from server:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'wtfserver' ]
2 info using npm@6.13.4
3 info using node@v8.17.0
4 verbose run-script [ 'prewtfserver', 'wtfserver', 'postwtfserver' ]
5 info lifecycle WTF-Adventure@1.0.6~prewtfserver: WTF-Adventure@1.0.6
6 info lifecycle WTF-Adventure@1.0.6~wtfserver: WTF-Adventure@1.0.6
7 verbose lifecycle WTF-Adventure@1.0.6~wtfserver: unsafe-perm in lifecycle true
8 verbose lifecycle WTF-Adventure@1.0.6~wtfserver: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/sites/*.expij.online/html/mmo.expij.online/html/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.dotnet/tools
9 verbose lifecycle WTF-Adventure@1.0.6~wtfserver: CWD: /var/www/sites/*.expij.online/html/mmo.expij.online/html
10 silly lifecycle WTF-Adventure@1.0.6~wtfserver: Args: [ '-c', 'nodemon --exec babel-node src/server/js/main.js' ]
11 silly lifecycle WTF-Adventure@1.0.6~wtfserver: Returned: code: 1  signal: null
12 info lifecycle WTF-Adventure@1.0.6~wtfserver: Failed to exec wtfserver script
13 verbose stack Error: WTF-Adventure@1.0.6 wtfserver: `nodemon --exec babel-node src/server/js/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid WTF-Adventure@1.0.6
15 verbose cwd /var/www/sites/*.expij.online/html/mmo.expij.online/html
16 verbose Linux 4.4.0-78-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "wtfserver"
18 verbose node v8.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error WTF-Adventure@1.0.6 wtfserver: `nodemon --exec babel-node src/server/js/main.js`
22 error Exit status 1
23 error Failed at the WTF-Adventure@1.0.6 wtfserver script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by design1online** [comment]
This has been fixed
