### ISSUE TITLE
Error on client start :(

### ISSUE THREAD

**Issue by eyupthebest** [design1online/WTF-Adventure#23]
ERROR in ./css/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./css/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (C:\Users\asus\Desktop\WTF-Adventure-master (1)\WTF-Adventure-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\asus\Desktop\WTF-Adventure-master (1)\WTF-Adventure-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\asus\Desktop\WTF-Adventure-master (1)\WTF-Adventure-master\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\Users\asus\Desktop\WTF-Adventure-master (1)\WTF-Adventure-master\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.sassLoader (C:\Users\asus\Desktop\WTF-Adventure-master (1)\WTF-Adventure-master\node_modules\sass-loader\lib\loader.js:46:72)
 @ ./css/main.scss 2:14-119
 @ multi ./css/main.scss ./src/client/config.json ./assets/data/sprites.json ./assets/data/maps/world_client.json

**Comment by design1online** [comment]
This has been fixed.

**Comment by eyupthebest** [comment]
can you help me set up? this is very detailed
